server:
 port: 8090
aoi:
 jwt:
  issuer: aoineko
  pkey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuTSP+mimt8IOGuoN6AQoGZgYFEMWydQF8DxdcLEuUonMkbcCgCV/OKB2fSgEESwVRP1AtHTtA60zwl0BPzc79XBvgQ5RfOnQg09yBMst/PfWxbCi3esGycNsse110KSdMPUB8UKS+ve2vyasRN6YoED5q75SSciFMGzlE+T2CrAvwdhY2Ji02c8mdKgWsBdS9jTrEf9CNnM3bIsFWs7UthEfgk/7obeV5tyHw1lD5R9R2YZXmtHmPUmh5Q74bo1xO0pqs4o5/+kVZ4qLHb5aoIbrhEc97Fq1pQvjpoogwZdY+jfxXsJVSXtVOmnVMK+pciEEXctGAp+FqzXArciTGQIDAQAB
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC5NI/6aKa3wg4a6g3oBCgZmBgUQxbJ1AXwPF1wsS5SicyRtwKAJX84oHZ9KAQRLBVE/UC0dO0DrTPCXQE/Nzv1cG+BDlF86dCDT3IEyy3899bFsKLd6wbJw2yx7XXQpJ0w9QHxQpL697a/JqxE3pigQPmrvlJJyIUwbOUT5PYKsC/B2FjYmLTZzyZ0qBawF1L2NOsR/0I2czdsiwVaztS2ER+CT/uht5Xm3IfDWUPlH1HZhlea0eY9SaHlDvhujXE7Smqzijn/6RVniosdvlqghuuERz3sWrWlC+OmiiDBl1j6N/FewlVJe1U6adUwr6lyIQRdy0YCn4WrNcCtyJMZAgMBAAECggEAeC9883IwJnVes+aJSbRQ1XMWxSdYRXc6t1BlDrlcJyHXSAQsMj6jFXtECSoLoZ0q3E9ASxrJqCYgvZOfOIe+eCMTqPtCtD4DGwNWKXg0isHGdRmQR1S6XfpcsgY3+0Kn41pLfWXHfed8hwUwq6yL/QrNOr9SJSFkFS3FZqihZgMdW3TXwlnCQa7CS3cjrzKLJ1hof2ftgS8oR1ZtsifCUs9zDPjxwIJ3XWrje5+k7vo/OWuoSrgx5GatSeDdClCeUYoqWX87+RAmodyl/MrQYKK3Mpjw7Gte7MaRtoOjJnV/qVK03CYVPlFBhZHU5QalCR+U9AL2EM8fkkSgE30+0QKBgQDy/9KjXFLfLspr5zN9wMTonBSF79zzwp2s3FeA8eRO3ZkWlUPQ95n2D9hCSqKQmTpZFJBCbiu8JxS8eRmBoUOe6Q2DA4816D4s1+MyW6PIKUpzzmG+F+zjwq4BZQMPb28LVK7DLFxYL6vPKXkMvZ9miKslc7PIMr9zcYoh8t2WrQKBgQDDHS3hmcJCKlv35SfkGOu40/NDKrcTtts+sQbjl2hKLXn99L8T3DbMYNkO/JYesoAaY81vbvGuLety9YUQWzXYZmBAciIrZDdCVbDk+NPa3VrqND5J59iKybhiBIfbtJIyPcPL5oxJs5qXAYEvpz+obk+2kx+oysUJIjMRJxQ3nQKBgBRrQMTvZhtQ8Dt+8wm3IBS3wNW8YSGukddLsKKqMNgbsNh/9HHjzHErxa1UXjKuXYPMwY6DeXNXCVwJBQaqiWcaCEOhEfCisk7MWVAK+UlBhvsSNY5mrkY5PqvpVAeBAqC+He1SlfPnFZXT01Mpv/I6u77q6QmCkineOZA+uzYFAoGAG4qr5lORA0v9bXGwftcxtwZcKVgHPcYrDp9ojInb09S1iq6YplIIfjMRkLcA7dZelNsPrbIodWDQAos7vEJTyHczEQXLYvqjfj6gWMHzDcr/QV4ciMwsWfL9jwB6uP21QVhMoiSqGuE6aiRxOuvN5ZWktO3xox70T0S/lqVAilUCgYBG8qPFk3Gcimg4WYBiaP/MRLRr/M3XXUOg7tn3ex9UmLWtIfbaw9lLFexMMcNSQTfDTrn3j07Ljq7W1KmatTvzHF0Hess+QohFflXq1J4FFoWaxaGVXRYTxA09FEdm+9uo3udhkF6quioUH6S8Pii1IwL+7gBC+zflJSriBWA9NQ==
mysql:
 url: jdbc:mysql://127.0.0.1:3306/aoineko?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
 username: aoineko
 password: 456123
 maxActive: 10
 minIdle: 2
 maxWait: 30000
 initialSize: 2
 testOnBorrow: false
 testOnReturn: false
 testWhileIdle: true
 timeBetweenEvictionRunsMillis: 30000
 minEvictableIdleTimeMillis: 1800000
 validationQuery: select 1
spring:
 thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  mode: LEGACYHTML5
  encoding: UTF-8